SELECT PP.GOSMACTIVITY, GA.STRATEGIES, AV.NAME, TO_CHAR(PPP.DATE,'Mon DD, YYYY') AS DATE, CONCAT(TO_CHAR(PPP.DATE+PPP.STARTTIME,'HH12:MI AM'),' - ',TO_CHAR(PPP.DATE+PPP.ENDTIME,'HH12:MI AM')) AS TIME
  FROM PROJECTPROPOSAL PP JOIN GOSMACTIVITY GA
                            ON PP.GOSMACTIVITY = GA.ID
      					  JOIN "ActivityVenue" AV      					  
                            ON PP.VENUE = AV.ID
    					  JOIN ProjectProposalProgramDesign PPP
    					  	ON PP.ID = PPP.ID

WHERE (GA.ACTIVITYTYPE = 2
   OR GA.ACTIVITYNATURE =1) 
  AND GA.GOSM NOT IN (SELECT ACTIVITY FROM AMTACTIVITYEVALUATION);