SELECT GA.STRATEGIES, GA.ID 
  FROM GOSMACTIVITY GA JOIN PROJECTPROPOSAL PP
			 ON GA.ID=PP.GOSMACTIVITY
 WHERE PP.STATUS=3
   AND GA.ACTIVITYTYPE=3
   AND GA.ID IN (SELECT GOSMACTIVITY 
		   FROM PROJECTPROPOSAL 
     		  WHERE (ACTUALDATESTART >= (SELECT DATESTART
					       FROM TERM
   				              WHERE NOW() >= DATESTART
						AND NOW() <= DATEEND ) 
   		    AND ACTUALDATEEND <= (SELECT DATEEND
   				   	    FROM TERM
   					   WHERE NOW() >= DATESTART
   				             AND NOW() <= DATEEND )  )  );