SELECT *
  FROM PROJECTPROPOSAL PP JOIN GOSMACTIVITY GA
    ON PP.GOSMACTIVITY = GA.ID
WHERE (GA.ACTIVITYTYPE = 2
   OR GA.ACTIVITYNATURE =1) 
  AND GA.GOSM NOT IN (SELECT ACTIVITY FROM AMTACTIVITYEVALUATION);