SELECT GA.STRATEGIES, GA.ID, G.STUDENTORGANIZATION AS organization
  FROM GOSMACTIVITY GA JOIN PROJECTPROPOSAL PP
			                   ON GA.ID=PP.GOSMACTIVITY
                       JOIN GOSM G
                         ON GA.GOSM=G.ID
 WHERE PP.STATUS=3
   AND GA.ACTIVITYTYPE=3
   AND GA.ID IN (SELECT GOSMACTIVITY 
		   FROM PROJECTPROPOSAL 
     		  WHERE (ACTUALDATESTART >= (SELECT DATESTART
					       FROM TERM
   				              WHERE NOW() >= DATESTART
						AND NOW() <= DATEEND ) 
   		    AND ACTUALDATEEND <= (SELECT DATEEND
   				   	    FROM TERM
   					   WHERE NOW() >= DATESTART
   				             AND NOW() <= DATEEND )  )  );