SELECT COUNT(PP.ID) as approved
FROM GOSM G JOIN GOSMACTIVITY GA
	      ON G.ID = GA.GOSM
	    JOIN PROJECTPROPOSAL PP
	      ON GA.ID = PP.GOSMACTIVITY
WHERE G.STUDENTORGANIZATION = ${org}
  AND PP.STATUS = 3
GROUP BY GA.GOSM;