SELECT *
  FROM PROJECTPROPOSALATTACHMENT
 WHERE PROJECTPROPOSAL =${projectId}
   AND SEQUENCE = (SELECT MAX(SEQUENCE)
   	 				 FROM PROJECTPROPOSALATTACHMENT
   	 			    WHERE PROJECTPROPOSAL =${projectId}
   	 			    )