SELECT *
  FROM PROJECTPROPOSALATTACHMENT PPA JOIN DOCUMENTATTACHMENTREQUIREMENT DAR
  									   ON PPA.REQUIREMENT = DAR.ID
 WHERE PPA.PROJECTPROPOSAL =${projectId}
   AND PPA.SEQUENCE = (SELECT MAX(SEQUENCE)
   	 				 FROM PROJECTPROPOSALATTACHMENT
   	 			    WHERE PROJECTPROPOSAL =${projectId}
   	 			    )