SELECT AN.NAME AS nature, AT.NAME AS type, GA.STRATEGIES AS strategies, SO.NAME AS orgname, PP.VENUE AS venue,
	   PP.ENMP AS enmp, PP.ENP AS enp, GA.OBJECTIVES AS objectives, PP.CONTEXT AS context, PP.ID as id, 
	   PP.SOURCEFUNDOTHER as sourcefundother, PP.SOURCEFUNDPARTICIPANTFEE AS sourcefundparticipantfee, 
	   PP.SOURCEFUNDORGANIZATIONAL, PP.ACCUMULATEDOPERATIONALFUNDS as accumulatedoperationalfunds,
	   PP.ACCUMULATEDDEPOSITORYFUNDS AS accumulateddepositoryfunds, PP.ORGANIZATIONFUNDOTHERSOURCE AS organizationfundothersource
FROM ((SELECT * FROM PROJECTPROPOSAL
 WHERE STATUS =2
 AND dateStatusModified IS NULL
 ORDER BY dateSubmitted) 
UNION
  (SELECT *
  FROM PROJECTPROPOSAL
  WHERE STATUS =2
  AND dateStatusModified IS NOT NULL 
  ORDER BY dateStatusModified)
  LIMIT 1) PP LEFT JOIN GOSMACTIVITY GA
					 ON PP.GOSMACTIVITY = GA.ID
				   JOIN ACTIVITYNATURE AN
				     ON GA.ACTIVITYNATURE=AN.ID
				   JOIN ACTIVITYTYPE AT
				     ON GA.ACTIVITYTYPE=AT.ID
				   JOIN GOSM G
				     ON G.ID=GA.GOSM
				   JOIN STUDENTORGANIZATION SO
				     ON SO.ID=G.STUDENTORGANIZATION;