SELECT (SUM(SOURCEFUNDOTHER)+SUM(SOURCEFUNDPARTICIPANTFEE)+SUM(SOURCEFUNDORGANIZATIONAL)) AS PROJECTEDCOST
  FROM PROJECTPROPOSAL
 WHERE GOSMACTIVITY IN (SELECT ID
 						  FROM GOSMACTIVITY
 						 WHERE GOSM=${gosm})