SELECT A.IDNUMBER, A.FIRSTNAME, A.LASTNAME 
  FROM ACCOUNT A JOIN ORGANIZATIONOFFICER OO
		   ON A.IDNUMBER=OO.IDNUMBER
	  	 JOIN ORGANIZATIONROLE ORL
	 	   ON ORL.ID=OO.ROLE
 WHERE ORL.ORGANIZATION=${organization};